#!/bin/sh

# [ML] will not work for now, since everything goes
# into /usr/share/legalcase ... which is later chown'ed to www-data,
# which is a REALLY bad idea, /usr is not for data (conf,logs,..) !
# 
# chgrp www-data /var/www/legalcase/log
# chgrp www-data /var/www/legalcase/inc/data/
# chgrp www-data /var/www/legalcase/inc/config/

if [ -d /etc/apache ]
then
	cd /etc/apache

	if [ ! -L legalcase.conf ]
	then
		ln -s /usr/share/legalcase/apache/legalcase.conf
	fi

	echo "Include /etc/apache/legalcase.conf" >> /etc/apache/httpd.conf

	# [ML] If php4/php5 is installed, then it should already be active, no?
	# messy!
	# apache-modconf apache enable mod_php4
fi

if [  -d /etc/apache2 ]
then
	cd /etc/apache2/sites-enabled/

	if [ ! -L legalcase.conf ]
	then
		ln -s /usr/share/legalcase/apache2/legalcase.conf
	fi

	# [ML] If php4/php5 is installed, then it should already be active, no?
	# messy!
	# apache-modconf apache enable mod_php4
fi

if [  -d /etc/apache-ssl ]
then
	cd /etc/apache-ssl

	if [ ! -L legalcase.conf ]
	then
		ln -s /usr/share/legalcase/apache/legalcase.conf
	fi

	echo "Include /etc/apache-ssl/legalcase.conf" >> /etc/apache-ssl/httpd.conf

	# [ML] If php4/php5 is installed, then it should already be active, no?
	# messy!
	apache-modconf apache-ssl enable mod_php4
fi
				
chown -R www-data:www-data /usr/share/legalcase/


### Activate on mysql extension, if necessary
IFS=':'
PHP4CONF="/etc/php4/apache/php.ini:/etc/php4/apache2/php.ini:/etc/php5/apache2/php.ini"

for file in $PHP4CONF; do
	if [ -f $file ]; then
		IS_ACTIVE=`grep mysql.so $file | grep extension | grep -v "^;"`

		if [ -z $IS_ACTIVE ]; then
			echo "extension=mysql.so" >> $file
			echo "$file: MySQL extension was activated"
		fi
	fi
done

### restart apache server
echo " "
echo "Restarting the apache server(s)"
sleep 0.2

if [ -e /etc/init.d/apache ]
then
	/etc/init.d/apache restart
fi
if [ -e /etc/init.d/apache2 ]
then
	/etc/init.d/apache2 restart
fi
if [ -e /etc/init.d/apache-ssl ]
then
	/etc/init.d/apache-ssl restart
fi

# The dialog(1) was hiding the console, where possible errors are shown..
echo -e "\n"
echo -e "** The Legal Case Management (LCM) installation is complete."
echo -e "** You can access it using your Web browser at the following location:"
echo -e "  http://`hostname`/legalcase.\n"
echo -e "** Since this Debian package is experimental, we would appreciate your feedback regarding the package: legalcase-devel@lists.sf.net"
echo -e "\n"

